#SERVER
server:
  port: 8081
  servlet:
    context-path: /api
      # context-path: parte di path che si frappone automaticamente tra host ed endpoint
      # http://{hostname}:{port}/{context-path}/{uri}
    # http://localhost:8081/api/....
  compression:
    enabled: true
    min-response-size: 2KB

# SPRING BOOT + DATABASE + MAIL
spring:
  application:
    name: myblog

  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
        # create-drop: crea tabelle all'avvio dell'applicazione e le distugge quando la stoppo
        # validated: confronta le entità del progetto con le tabelle del db: se ci sono anomalie, solleva eccezione
        # none: da usare in ambiente di produzione: non viene riportata alcuna modifica al db
      # update: aggiorna il db con le tabelle/colonne nuove; non elimina colonne che non hanno più corrispondenza con l'entità
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  # all'avvio dell'applicazione viene eseguito data.sql presente in resource
  sql.init.mode: never

  mail:
    # host: smtp.gmail.com
    host: ${MAIL_SMTP}
    # port: 587
    port: ${MAIL_PORT}
    # Nel caso di google lo username corrisponde all'email SENZA '@gmail.com'
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true

# LOGGING
logging:
  level:
    it.cgmconsulting: info
    org:
      springframework:
        boot: info
        security: debug
    org.hibernate.orm.jdbc.bind: trace

# CUSTOM PROPERTIES
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      # 4 ORE in millisecondi
      expiration: 14400000

  image:
    avatar:
      # dimensione dell'immagine in byte -> 10240 = 10kb
      size: 10240
      width: 512
      height: 512
      extensions: image/jpg,image/jpeg,image/png,image/webp



